//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualExplorerUnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManualExplorerUnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 200 OK
        ///X-Backside-Transport: OK OK
        ///Connection: Keep-Alive
        ///Transfer-Encoding: chunked
        ///Pragma: no-cache
        ///X-Global-Transaction-ID: 2045854737
        ///Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
        ///Content-Type: text/html
        ///Date: Wed, 02 Nov 2016 23:47:37 GMT
        ///Expires: Thu, 19 Nov 1981 08:52:00 GMT
        ///Set-Cookie: survey_done=true
        ///Server: Apache
        ///
        ///&lt;form id=&quot;survey_form&quot; style=&quot;padding:10px;&quot;&gt;
        ///
        ///			&lt;br&gt;&lt;br&gt;
        ///			Thank you for your feedback. The following information was added  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AltoroDifChunkedResponse {
            get {
                return ResourceManager.GetString("AltoroDifChunkedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /bank/login.aspx HTTP/1.1
        ///Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/msword, application/xaml+xml, application/vnd.ms-xpsdocument, application/x-ms-xbap, application/x-ms-application, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, */*
        ///Referer: http://www.altoromutual.com/
        ///Accept-Language: en-us
        ///Host: www.altoromutual.com
        ///Cookie: ASP.NET_SessionId=gyixpjmizsnswazv5zunxial; amSessionId=1975473225
        ///Connection: Keep-Alive
        ///User-Agen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AltoroLoginPageRequest {
            get {
                return ResourceManager.GetString("AltoroLoginPageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Begin Thread  5128[140c] &lt;Tue, 04 Jan 11, 07:20:47:250&gt; ----
        ///====&gt; ************************************************
        ///====&gt; ********  APPSCAN STARTING NEW SESSION  ********
        ///====&gt; ************************************************
        ///---- End Thread  5128[140c] ----
        ///---- Begin Thread  7204[9ac] &lt;Thu, 06 Jan 11, 13:52:42:651&gt; ----
        ///====&gt; ************************************************
        ///====&gt; ********  APPSCAN STARTING NEW SESSION  ********
        ///====&gt; ************************************************
        ///---- End  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppScanTraffic_log {
            get {
                return ResourceManager.GetString("AppScanTraffic_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 401 Authorization Required
        ///Server: HTTPd/1.0
        ///Date: Sat, 27 Nov 2004 10:18:15 GMT
        ///WWW-Authenticate: NTLM
        ///WWW-Authenticate: Basic realm=&quot;Secure Area&quot;
        ///Content-Type: text/html
        ///Content-Length: 311
        ///
        ///&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;
        /// &quot;http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd&quot;&gt;
        ///&lt;HTML&gt;
        ///  &lt;HEAD&gt;
        ///    &lt;TITLE&gt;Error&lt;/TITLE&gt;
        ///    &lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html; charset=ISO-8859-1&quot;&gt;
        ///  &lt;/HEAD&gt;
        ///  &lt;BODY&gt;&lt;H1&gt;401 Unauthorized.&lt;/H1&gt;&lt;/BODY&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string basicauthresponse {
            get {
                return ResourceManager.GetString("basicauthresponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 200 OK
        ///Content-Type: text/plain
        ///Transfer-Encoding: chunked
        ///
        ///25
        ///This is the data in the first chunk
        ///
        ///1C
        ///and this is the second one
        ///
        ///3
        ///con
        ///8
        ///sequence
        ///0.
        /// </summary>
        internal static string ChunkedResponse {
            get {
                return ResourceManager.GetString("ChunkedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the data in the first chunk
        ///and this is the second one
        ///consequence.
        /// </summary>
        internal static string DecodedChunkedBody {
            get {
                return ResourceManager.GetString("DecodedChunkedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST / HTTP/1.1
        ///Host: 9.21.123.145
        ///User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
        ///Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        ///Accept-Language: en-US,en;q=0.5
        ///Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        ///Content-Length: 134
        ///Connection: keep-alive
        ///Pragma: no-cache
        ///Cache-Control: no-cache
        ///
        ///{method%3A%22QRadar.getAlertMessages%22%2Cparams%3Anull%2CCSRF%3A%2297199c9c-5df4-46cd-b0f1-f4fbc8d2381c%22%2Cid%3A%2285%22}  .
        /// </summary>
        internal static string encJSONPostRequest {
            get {
                return ResourceManager.GetString("encJSONPostRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET {0} HTTP/{1}
        ///Host: {2}:{3}
        ///
        ///.
        /// </summary>
        internal static string GETRequestTemplate {
            get {
                return ResourceManager.GetString("GETRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 200 OK
        ///Content-Type: text/plain
        ///Transfer-Encoding: chunked
        ///
        ///25
        ///This is the data in the first chunk
        ///
        ///1C
        ///and this is the second one
        ///
        ///2
        ///con
        ///8
        ///sequence
        ///0.
        /// </summary>
        internal static string IncorrectChunkedResponse {
            get {
                return ResourceManager.GetString("IncorrectChunkedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET http://[2002:917:2df7::917:2df7]/ase HTTP/1.1
        ///Accept: image/jpeg, image/gif, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, application/msword, */*
        ///Accept-Language: en-US
        ///Accept-Encoding: gzip, deflate
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET4.0C; .NET4.0E; .NET CLR 3.5.30729; .NET CLR 3.0.30729)
        ///Proxy-Connection: Keep-Alive
        ///Host: [2002:917:2df7::917:2df7].
        /// </summary>
        internal static string IPV6Request {
            get {
                return ResourceManager.GetString("IPV6Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET https://[2002:917:2df7::917:2df7]:9443/jts HTTP/1.1
        ///Accept: image/jpeg, image/gif, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, application/msword, */*
        ///Accept-Language: en-US
        ///Accept-Encoding: gzip, deflate
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET4.0C; .NET4.0E; .NET CLR 3.5.30729; .NET CLR 3.0.30729)
        ///Proxy-Connection: Keep-Alive
        ///Host: [2002:917:2df7::917:2df7]:9443.
        /// </summary>
        internal static string IPv6RequestWithPort {
            get {
                return ResourceManager.GetString("IPv6RequestWithPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachineName=&quot;WEBVWN11P&quot; ProductVersion=&quot;ASE 5.60.0.491&quot; CreateDateTime=&quot;12/09/2010 13:53:48.587&quot;
        ///MessageType  DateTime                   ApplicationName      ProcessID  ThreadID   ItemID     ComponentName                    MessageCode  MessageText    MessageLocation    Instance           
        ///verbose      &quot;12/08/2010 17:55:59.581&quot;  AgentHost.exe        3292       3720       748        &quot;Scan Engine&quot;                    0x0          &quot;Queue is going to be limited to 100&quot; &quot;ScanDirector&quot;     &quot;&quot;                 
        ///v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemLog {
            get {
                return ResourceManager.GetString("ItemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST /bank/login.aspx?x=1&amp;y=2&amp;true HTTP/1.1
        ///Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/msword, application/xaml+xml, application/vnd.ms-xpsdocument, application/x-ms-xbap, application/x-ms-application, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, */*
        ///Referer: http://www.altoromutual.com/
        ///Accept-Language: en-us
        ///Host: www.altoromutual.com
        ///Cookie: ASP.NET_SessionId=gyixpjmizsnswazv5zunxial; amSessionId=1975473225
        ///Connection: Keep-Al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONPostRequest {
            get {
                return ResourceManager.GetString("JSONPostRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --uuid:9cd759e9-e0e1-43e1-abc4-c9f3db8601ad
        ///Content-Type: application/xop+xml; charset=UTF-8; type=&quot;text/xml&quot;;
        ///Content-Transfer-Encoding: binary
        ///Content-ID: &lt;1&gt;
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;&lt;FileScope&gt;&lt;authToken&gt;06c728540c561000c821fd4e19fc19fc&lt;/authToken&gt;&lt;content&gt;&lt;xop:Include xmlns:xop=&quot;http://www.w3.org/2004/08/xop/include&quot; href=&quot;cid:f3f23ea5-178f-4995-96fb-96b103686533-1@cxf.apache.org&quot;/&gt;&lt;/content&gt;&lt;options&gt;0&lt;/options&gt;&lt;path&gt;/user/environments/AppScanTest111/cells/standAlone [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultiPartData {
            get {
                return ResourceManager.GetString("MultiPartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST /rafservices/EFS/put HTTP/1.1
        ///Content-Type: multipart/related; type=&quot;application/xop+xml&quot;; boundary=&quot;uuid:9cd759e9-e0e1-43e1-abc4-c9f3db8601ad&quot;; start=&quot;&lt;1&gt;&quot;; start-info=&quot;text/xml&quot;
        ///Accept: multipart/related
        ///User-Agent: Apache CXF 2.3.3
        ///Cache-Control: no-cache
        ///Pragma: no-cache
        ///Connection: keep-alive
        ///Content-Length: 1095
        ///
        ///
        ///--uuid:9cd759e9-e0e1-43e1-abc4-c9f3db8601ad
        ///Content-Type: application/xop+xml; charset=UTF-8; type=&quot;text/xml&quot;;
        ///Content-Transfer-Encoding: binary
        ///Content-ID: &lt;1&gt;
        ///
        ///&lt;?xml ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultipartRequest {
            get {
                return ResourceManager.GetString("MultipartRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET http://www.nytimes.com/glogin?URI=http://www.nytimes.com/2013/01/15/world/asia/china-allows-media-to-report-alarming-air-pollution-crisis.html&amp;OQ=_rQ3D0&amp;OP=4b396406Q2Fk5vpkJspkYYYk4pjAkQ255V!r55pLkLQ26Q24wkQ26Q24kQ24Q7DkY5rAQ25kQ5B!)Q5BkV4)JQ5B,Q5BAA5Y!,jQ5DQ25)Q5B,p5,rQ5Dv5rp,Q5BAQ5Brj)Jt,Q5B)r,v5AAmp)5J,Vr)!)!B4pjA HTTP/1.1
        ///Host: www.nytimes.com
        ///User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0
        ///Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NyTimesRequest {
            get {
                return ResourceManager.GetString("NyTimesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST http://www.altoromutual.com/bank/login.aspx?x=1&amp;y=2&amp;true HTTP/1.1
        ///Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/msword, application/xaml+xml, application/vnd.ms-xpsdocument, application/x-ms-xbap, application/x-ms-application, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, */*
        ///Referer: http://www.altoromutual.com/
        ///Accept-Language: en-us
        ///Host: www.altoromutual.com
        ///Cookie: ASP.NET_SessionId=gyixpjmizsnswazv5zunxial; amSessionId=1975 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string POSTRequest {
            get {
                return ResourceManager.GetString("POSTRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST {0} HTTP/{1}
        ///Host: {2}:{3}
        ///Content-length: {4}
        ///
        ///{5}.
        /// </summary>
        internal static string POSTRequestTemplate {
            get {
                return ResourceManager.GetString("POSTRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /bank/login.aspx? HTTP/1.1
        ///Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/msword, application/xaml+xml, application/vnd.ms-xpsdocument, application/x-ms-xbap, application/x-ms-application, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, */*
        ///Referer: http://www.altoromutual.com/
        ///Accept-Language: en-us
        ///Host: www.altoromutual.com
        ///Cookie: ASP.NET_SessionId=gyixpjmizsnswazv5zunxial; amSessionId=1975473225
        ///Connection: Keep-Alive
        ///User-Age [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestWithEmptyQUery {
            get {
                return ResourceManager.GetString("RequestWithEmptyQUery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET http://l.yimg.com/bt/api/res/1.2/RMHM2QL7.RMHwFwGPO0kug--/YXBwaWQ9eW5ld3M7Y2g9MjQ4MTtjcj0xO2N3PTM3MjE7ZHg9MDtkeT0wO2ZpPXVsY3JvcDtoPTQyMTtxPTg1O3c9NjMw/http://media.zenfs.com/en_us/News/ap_webfeeds/57cdb3e9907f9605290f6a706700d101.jpg HTTP/1.1
        ///Host: l.yimg.com
        ///User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:19.0) Gecko/20100101 Firefox/19.0
        ///Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        ///Accept-Language: en-US,en;q=0.5
        ///Accept-Encoding: gzip, deflate
        ///Connection: keep-alive [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestWithHttpInPath {
            get {
                return ResourceManager.GetString("RequestWithHttpInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /bank/login.aspx?x=1&amp;y=2&amp;true HTTP/1.1
        ///Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/msword, application/xaml+xml, application/vnd.ms-xpsdocument, application/x-ms-xbap, application/x-ms-application, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, */*
        ///Referer: http://www.altoromutual.com/
        ///Accept-Language: en-us
        ///Host: www.altoromutual.com
        ///Connection: Keep-Alive
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)
        ///.
        /// </summary>
        internal static string RequestWithQuery {
            get {
                return ResourceManager.GetString("RequestWithQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:web=&quot;http://webservices2.focalpoint.telelogic.com&quot;&gt;
        ///   &lt;soapenv:Header/&gt;
        ///   &lt;soapenv:Body&gt;
        ///      &lt;web:authenticate&gt;
        ///         &lt;web:username&gt;jsmith&lt;/web:username&gt;
        ///         &lt;web:password&gt;Demo1234&lt;/web:password&gt;
        ///      &lt;/web:authenticate&gt;
        ///   &lt;/soapenv:Body&gt;
        ///&lt;/soapenv:Envelope&gt;.
        /// </summary>
        internal static string SOAPPost {
            get {
                return ResourceManager.GetString("SOAPPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST /fp/services2/FPServices HTTP/1.1
        ///Host: 9.124.108.45:6510
        ///Accept-Encoding: gzip,deflate
        ///Content-Type: text/xml;charset=UTF-8
        ///SOAPAction: &quot;urn:authenticate&quot;
        ///
        ///&lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:web=&quot;http://webservices2.focalpoint.telelogic.com&quot;&gt;
        ///   &lt;soapenv:Header/&gt;
        ///   &lt;soapenv:Body&gt;
        ///      &lt;web:authenticate&gt;
        ///         &lt;web:username&gt;jsmith&lt;/web:username&gt;
        ///         &lt;web:password&gt;Demo1234&lt;/web:password&gt;
        ///      &lt;/web:authenticate&gt;
        ///   &lt;/soapenv:Body&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOAPRequest {
            get {
                return ResourceManager.GetString("SOAPRequest", resourceCulture);
            }
        }
    }
}
