//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficViewerControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrafficViewerControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Reverse Proxy.
        /// </summary>
        internal static string BinaryReverseProxy {
            get {
                return ResourceManager.GetString("BinaryReverseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Viewer Message.
        /// </summary>
        internal static string BoxTitle {
            get {
                return ResourceManager.GetString("BoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Proxy.
        /// </summary>
        internal static string CaptureProxy {
            get {
                return ResourceManager.GetString("CaptureProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will clear both the source and the traffic viewer file. Are you sure?.
        /// </summary>
        internal static string ClearWarning {
            get {
                return ResourceManager.GetString("ClearWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Log Sync Page&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///			a.link1:link {color:Black; text-decoration: none; font-size:11px; font-family: Courier New; cursor: pointer;}
        ///			a.link1:visited {color:Black; text-decoration: none; font-size:11px; font-family: Courier New; cursor: pointer;}
        ///			a.link1:hover {color:red; text-decoration: none; font-size:11px; font-family: Courier New; cursor: pointer;}
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CollapsibleElementsPage {
            get {
                return ResourceManager.GetString("CollapsibleElementsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A communication error has occured at request id: {0}. Would you like to continue?.
        /// </summary>
        internal static string CommunicationErrorQuestion {
            get {
                return ResourceManager.GetString("CommunicationErrorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error..
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive By Attack Proxy.
        /// </summary>
        internal static string DriveByAttackProxy {
            get {
                return ResourceManager.GetString("DriveByAttackProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new description:.
        /// </summary>
        internal static string EnterNewDescription {
            get {
                return ResourceManager.GetString("EnterNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new scheme.
        /// </summary>
        internal static string EnterNewScheme {
            get {
                return ResourceManager.GetString("EnterNewScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect host.
        /// </summary>
        internal static string ErrorHost {
            get {
                return ResourceManager.GetString("ErrorHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected document has no Dom..
        /// </summary>
        internal static string ErrorNoDom {
            get {
                return ResourceManager.GetString("ErrorNoDom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dom Id has been calculated for this document.
        /// </summary>
        internal static string ErrorNoDomId {
            get {
                return ResourceManager.GetString("ErrorNoDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while opening the Traffic Viewer file. Check the log for more information.
        /// </summary>
        internal static string ErrorOpen {
            get {
                return ResourceManager.GetString("ErrorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect port.
        /// </summary>
        internal static string ErrorPort {
            get {
                return ResourceManager.GetString("ErrorPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred check the log for more information..
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occured. Please check the log for the exception message..
        /// </summary>
        internal static string ExceptionHasOccured {
            get {
                return ResourceManager.GetString("ExceptionHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting traffic: &apos;{0}&apos;..
        /// </summary>
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening on host: {0} port: {1}. Please set your browser proxy settings to this address to capture requests..
        /// </summary>
        internal static string ExternalBrowserTextStarted {
            get {
                return ResourceManager.GetString("ExternalBrowserTextStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy stopped.
        /// </summary>
        internal static string ExternalBrowserTextStopped {
            get {
                return ResourceManager.GetString("ExternalBrowserTextStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSS/CSRF Test Page.
        /// </summary>
        internal static string FormExploiter {
            get {
                return ResourceManager.GetString("FormExploiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET {0} HTTP/1.1
        ///Accept-Language: en-us
        ///Accept: */*
        ///Host: {1}:{2}
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)
        ///.
        /// </summary>
        internal static string FormRequestString {
            get {
                return ResourceManager.GetString("FormRequestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 200 OK
        ///Content-Type: text/html;charset=UTF8
        ///Content-Language: en-US
        ///
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;{4}&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body onLoad=&quot;if(&apos;{0}&apos; === &apos;none&apos;) submitForm();&quot;&gt;
        ///		&lt;div style=&quot;display:{0}&quot;&gt;
        ///			&lt;input style=&quot;width:100%&quot; id=&quot;targetUrl&quot; name=&quot;targetUrl&quot; value=&quot;{1}&quot;/&gt;&lt;br&gt;
        ///			&lt;button onClick=&quot;submitForm()&quot;&gt;Submit&lt;/button&gt;
        ///		&lt;/div&gt;
        ///		&lt;script&gt;
        ///
        ///			function submitForm(){{
        ///
        ///				var postData = {6};
        ///				var httpRequest = new XMLHttpRequest();
        ///				httpRequest.onreadystatechange = function() {{ 
        ///				}};  
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormResponse {
            get {
                return ResourceManager.GetString("FormResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuzzer.
        /// </summary>
        internal static string Fuzzer {
            get {
                return ResourceManager.GetString("Fuzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing file {0}. Exception message: {1}.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to restart before the settings can take effect..
        /// </summary>
        internal static string InfoNeedsRestart {
            get {
                return ResourceManager.GetString("InfoNeedsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the url.
        /// </summary>
        internal static string InputUrl {
            get {
                return ResourceManager.GetString("InputUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url might be invalid.
        /// </summary>
        internal static string InputUrlInvalid {
            get {
                return ResourceManager.GetString("InputUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string might be incorrectly encoded or not encoded using this method.
        /// </summary>
        internal static string InvalidEncoding {
            get {
                return ResourceManager.GetString("InvalidEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Path.
        /// </summary>
        internal static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected text is not valid xml.
        /// </summary>
        internal static string InvalidXML {
            get {
                return ResourceManager.GetString("InvalidXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a log file to syncronize with. Traffic Viewer will automatically align the current request with log events that happened at the same time..
        /// </summary>
        internal static string LogSyncDefaultMessage {
            get {
                return ResourceManager.GetString("LogSyncDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon lupa {
            get {
                object obj = ResourceManager.GetObject("lupa", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man in the Middle.
        /// </summary>
        internal static string ManInTheMiddle {
            get {
                return ResourceManager.GetString("ManInTheMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Explore Browser.
        /// </summary>
        internal static string ManualExploreBrowser {
            get {
                return ResourceManager.GetString("ManualExploreBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause1 {
            get {
                object obj = ResourceManager.GetObject("pause1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum requests that can be re-sent at a time: {0}.
        /// </summary>
        internal static string PlaybackLimit {
            get {
                return ResourceManager.GetString("PlaybackLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests found: {0} / Requests Missed: {1} / Requests Total: {2}.
        /// </summary>
        internal static string ProxyConsoleStatistics {
            get {
                return ResourceManager.GetString("ProxyConsoleStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests loaded: {0}.
        /// </summary>
        internal static string RequestsLoadedText {
            get {
                return ResourceManager.GetString("RequestsLoadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request was trapped!.
        /// </summary>
        internal static string RequestTrappedTitle {
            get {
                return ResourceManager.GetString("RequestTrappedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string RequestViewSaveChangesMenu {
            get {
                return ResourceManager.GetString("RequestViewSaveChangesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request was trapped. You can now switch to the traffic editor and  edit the request. When you are done editing press F2 to commit your changes and click Release..
        /// </summary>
        internal static string RequestWasTrapped {
            get {
                return ResourceManager.GetString("RequestWasTrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A response was trapped!.
        /// </summary>
        internal static string ResponseTrappedTitle {
            get {
                return ResourceManager.GetString("ResponseTrappedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A response was trapped. You can now switch to the traffic editor and  edit the response. When you are done editing press F2 to commit your changes and click Release..
        /// </summary>
        internal static string ResponseWasTrapped {
            get {
                return ResourceManager.GetString("ResponseWasTrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Proxy.
        /// </summary>
        internal static string ReverseProxy {
            get {
                return ResourceManager.GetString("ReverseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 200 OK
        ///Content-Type: text/html;charset=UTF8
        ///Content-Language: en-US
        ///Server: IIS/7.0
        ///
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Traffic Viewer Test Response&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Traffic Viewer Test Response&lt;/h1&gt;
        ///		
        ///		&lt;a href=&quot;mylink&quot;&gt;Sample Link&lt;/a&gt; &lt;br&gt;
        ///		Sample Form
        ///		&lt;hr&gt;
        ///		&lt;form&gt;
        ///			User: &lt;input type=&quot;text&quot; id=&quot;user&quot; name=&quot;user&quot; value=&quot;user&quot;&gt;&lt;br&gt;
        ///			Pass: &lt;input type=&quot;password&quot; id=&quot;pass&quot; name=&quot;user&quot; value=&quot;user&quot;&gt;&lt;br&gt;
        ///			&lt;input type=&quot;submit&quot; value=&quot;Submit&quot;&gt;
        ///		&lt;/form&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SampleHttpResponse {
            get {
                return ResourceManager.GetString("SampleHttpResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept-Language: en-us
        ///Accept: */*
        ///Host: demo.testfire.net
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32).
        /// </summary>
        internal static string SampleRequestHeaders {
            get {
                return ResourceManager.GetString("SampleRequestHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_6530 {
            get {
                object obj = ResourceManager.GetObject("Save_6530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Crawler.
        /// </summary>
        internal static string ScriptCrawlerExploiter {
            get {
                return ResourceManager.GetString("ScriptCrawlerExploiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one request.
        /// </summary>
        internal static string SelectOneRequest {
            get {
                return ResourceManager.GetString("SelectOneRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Attack Proxy.
        /// </summary>
        internal static string SequentialAttackProxy {
            get {
                return ResourceManager.GetString("SequentialAttackProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set selected Http Client. Defaulting to the Traffic Viewer one..
        /// </summary>
        internal static string SetHttpClientError {
            get {
                return ResourceManager.GetString("SetHttpClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowAllFiles_349 {
            get {
                object obj = ResourceManager.GetObject("ShowAllFiles_349", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Similarity: {0}%.
        /// </summary>
        internal static string SimilarityText {
            get {
                return ResourceManager.GetString("SimilarityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tail {
            get {
                object obj = ResourceManager.GetObject("tail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Proxy.
        /// </summary>
        internal static string TrackingProxy {
            get {
                return ResourceManager.GetString("TrackingProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic File Proxy.
        /// </summary>
        internal static string TrafficFileProxy {
            get {
                return ResourceManager.GetString("TrafficFileProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Viewer Request.
        /// </summary>
        internal static string TrafficViewerRequestDescription {
            get {
                return ResourceManager.GetString("TrafficViewerRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release ({0}).
        /// </summary>
        internal static string TrapRelease {
            get {
                return ResourceManager.GetString("TrapRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap untail {
            get {
                object obj = ResourceManager.GetObject("untail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection from the proxy to the site is untrusted. Would you like to continue?.
        /// </summary>
        internal static string UntrustedSSL {
            get {
                return ResourceManager.GetString("UntrustedSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for response....
        /// </summary>
        internal static string WaitingForResponse {
            get {
                return ResourceManager.GetString("WaitingForResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Traffic Server Forwarding might cause you to send attacks to public sites. Are you sure you want to do this?.
        /// </summary>
        internal static string WarnForwarding {
            get {
                return ResourceManager.GetString("WarnForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
