//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficViewerSDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrafficViewerSDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASE Manual Explore (EXD).
        /// </summary>
        internal static string ASEEXDCaption {
            get {
                return ResourceManager.GetString("ASEEXDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blackopscert {
            get {
                object obj = ResourceManager.GetObject("blackopscert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Parser.
        /// </summary>
        internal static string ConfigurationParserName {
            get {
                return ResourceManager.GetString("ConfigurationParserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT {0}:{1} HTTP/1.0
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30; .NET CLR 3.0.04506.648; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MS-RTC LM 8; .NET4.0C; .NET4.0E)
        ///Proxy-Connection: Keep-Alive
        ///Content-Length: 0
        ///Host: {0}:{1}
        ///Pragma: no-cache
        ///
        ///.
        /// </summary>
        internal static string ConnectRequest {
            get {
                return ResourceManager.GetString("ConnectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET {0} HTTP/1.1
        ///Accept: */*
        ///Host: {1}:{2}
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)
        ///.
        /// </summary>
        internal static string DefaultRequest {
            get {
                return ResourceManager.GetString("DefaultRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        internal static string ErrorCodeTitle {
            get {
                return ResourceManager.GetString("ErrorCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppScan Manual Explore (EXD).
        /// </summary>
        internal static string EXDCaption {
            get {
                return ResourceManager.GetString("EXDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAR Import.
        /// </summary>
        internal static string HarParserDescription {
            get {
                return ResourceManager.GetString("HarParserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har Parser.
        /// </summary>
        internal static string HarParserName {
            get {
                return ResourceManager.GetString("HarParserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Black Ops Error Message.
        /// </summary>
        internal static string HttpBlackOpsErrorMessage {
            get {
                return ResourceManager.GetString("HttpBlackOpsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Session Page.
        /// </summary>
        internal static string InSessionPage {
            get {
                return ResourceManager.GetString("InSessionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppScan Login Files (.login).
        /// </summary>
        internal static string LoginExporter {
            get {
                return ResourceManager.GetString("LoginExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Explore.
        /// </summary>
        internal static string ManualExplore {
            get {
                return ResourceManager.GetString("ManualExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Explore Request to Site.
        /// </summary>
        internal static string ManualExploreRequestDescription {
            get {
                return ResourceManager.GetString("ManualExploreRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Manual Explore Server. 
        ///Address:  {0}:{1} 
        ///Files directory: {2}
        ///Maxiumum recording sessions:  {3}
        ///Ignore certificate errors: {4}
        ///Default exclusions: {5}.
        /// </summary>
        internal static string ManualExploreServerStarting {
            get {
                return ResourceManager.GetString("ManualExploreServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Step Operations.
        /// </summary>
        internal static string MultiStep {
            get {
                return ResourceManager.GetString("MultiStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No login requests were found in your traffic data. You may need to edit the requests description..
        /// </summary>
        internal static string NoLoginRequestsFound {
            get {
                return ResourceManager.GetString("NoLoginRequestsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;parameter name=&quot;&quot; captureIndex=&quot;0&quot; customParameterName=&quot;treesel&quot; value=&quot;10aa52232760fbc152511&quot; type=&quot;BODY&quot; linkParamType=&quot;simplelink&quot; separator=&quot;&amp;amp;&quot; operator=&quot;=&quot; reportName=&quot;[treesel]&quot; /&gt;
        ///          &lt;parameter name=&quot;&quot; captureIndex=&quot;1&quot; customParameterName=&quot;treesel&quot; value=&quot;10aa52232760fbc152511&quot; type=&quot;BODY&quot; linkParamType=&quot;simplelink&quot; separator=&quot;&amp;amp;&quot; operator=&quot;=&quot; reportName=&quot;[treesel]_1&quot; /&gt;
        ///          &lt;parameter name=&quot;&quot; captureIndex=&quot;0&quot; customParameterName=&quot;webtreeid&quot; value=&quot;10aa52232760fbc152511&quot; type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParametersDefinitions {
            get {
                return ResourceManager.GetString("ParametersDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the site..
        /// </summary>
        internal static string ProxyErrorSendingRequestToTheSite {
            get {
                return ResourceManager.GetString("ProxyErrorSendingRequestToTheSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while sending request &apos;{0}&apos;.
        /// </summary>
        internal static string ProxyInternalError {
            get {
                return ResourceManager.GetString("ProxyInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occured in the proxy..
        /// </summary>
        internal static string ProxyInternalErrorGeneric {
            get {
                return ResourceManager.GetString("ProxyInternalErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Login.
        /// </summary>
        internal static string RecordedLoginPage {
            get {
                return ResourceManager.GetString("RecordedLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording started..
        /// </summary>
        internal static string RecordingStarted {
            get {
                return ResourceManager.GetString("RecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording stopped..
        /// </summary>
        internal static string RecordingStopped {
            get {
                return ResourceManager.GetString("RecordingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timeout.
        /// </summary>
        internal static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppScan Sequence Files (SEQ).
        /// </summary>
        internal static string SequenceExporter {
            get {
                return ResourceManager.GetString("SequenceExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secure connection to the target site failed..
        /// </summary>
        internal static string SSLConnectionFailed {
            get {
                return ResourceManager.GetString("SSLConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Log Parser.
        /// </summary>
        internal static string TrafficLogParserName {
            get {
                return ResourceManager.GetString("TrafficLogParserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Viewer Http Client.
        /// </summary>
        internal static string TrafficViewerHttpClientName {
            get {
                return ResourceManager.GetString("TrafficViewerHttpClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported from Uri.
        /// </summary>
        internal static string UriParserDescription {
            get {
                return ResourceManager.GetString("UriParserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET {0}?{1} HTTP/1.1
        ///Accept: */*
        ///Host: {2}:{3}
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)
        ///.
        /// </summary>
        internal static string UriParserGetRequest {
            get {
                return ResourceManager.GetString("UriParserGetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri Parser.
        /// </summary>
        internal static string UriParserName {
            get {
                return ResourceManager.GetString("UriParserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST {0} HTTP/1.1
        ///Accept: */*
        ///Host: {2}:{3}
        ///User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)
        ///
        ///{1}
        ///
        ///.
        /// </summary>
        internal static string UriParserPostRequest {
            get {
                return ResourceManager.GetString("UriParserPostRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;VariablesDefinitions&gt;
        ///        &lt;VariableDefinition IsRegularExpression=&quot;False&quot; Name=&quot;treesel&quot;&gt;
        ///          &lt;VariableType&gt;Custom&lt;/VariableType&gt;
        ///          &lt;Hosts /&gt;
        ///          &lt;Path /&gt;
        ///          &lt;Comments /&gt;
        ///          &lt;RequestIgnoreStatus&gt;Value&lt;/RequestIgnoreStatus&gt;
        ///          &lt;EntityIgnoreStatus&gt;Value&lt;/EntityIgnoreStatus&gt;
        ///          &lt;ExcludeFromTest&gt;False&lt;/ExcludeFromTest&gt;
        ///          &lt;SessionIDEnabled&gt;True&lt;/SessionIDEnabled&gt;
        ///          &lt;CaptureName /&gt;
        ///          &lt;CaptureIndex&gt;-1&lt;/CaptureIndex&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VariableDefinitions {
            get {
                return ResourceManager.GetString("VariableDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebRequest.
        /// </summary>
        internal static string WebRequest {
            get {
                return ResourceManager.GetString("WebRequest", resourceCulture);
            }
        }
    }
}
